door
0oWoodenDooro0/LevelDevil pull request #14
Opened 2024-03-08 04:08 UTC by fiersungod

2024-03-08 04:56 UTC, 0oWoodenDooro0 commented on src/Door.cpp
> +    }
加一個bool 判斷有沒有通關 有通關就撥放動畫 
不要用collision偵測角色還是會動

2024-03-08 04:57 UTC, 0oWoodenDooro0 requested changes
改完就可以了

2024-03-13 02:58 UTC, fiersungod commented
執行時發生
錯誤	C2665	'Util::Image::Image': 沒有任何多載函式可以轉換所有引數類型 
目前原因未知

2024-03-13 03:24 UTC, fiersungod commented
bug 已修復 door已更改

2024-03-13 03:26 UTC, fiersungod commented
有加一個按鈕框架可以順便看一下

2024-03-14 13:17 UTC, 0oWoodenDooro0 commented
之後不相關的兩個東西不要放同一個branch
再開一個pr就好

2024-03-14 13:25 UTC, 0oWoodenDooro0 commented
你先把Button.hpp和Button.cpp去掉

2024-03-15 02:34 UTC, 0oWoodenDooro0 approved these changes

2024-03-15 02:37 UTC, merged